name = "one-liner-nippo-backend"
main = "src/index.ts"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[vars]
JWT_SECRET = "your-super-secret-jwt-key-change-this-in-production"

[env.development]
[[env.development.d1_databases]]
binding = "DB"
database_name = "one-liner-nippo-dev"
database_id = "one-liner-nippo-dev"

[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "one-liner-nippo-prod"
database_id = "one-liner-nippo-prod"

[[d1_databases]]
binding = "DB"
database_name = "one-liner-nippo-dev"
database_id = "one-liner-nippo-dev"